server:
  port: 8080
  servlet:
    context-path: "/pizza"
    session:
      timeout: 30m
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.HSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
